#!/bin/bash

echo "Starting JACK Audio Connection Kit..."

SERVICE="qjackctl"
RESULT=`ps -ae | sed -n /${SERVICE}/p`

if [ "${RESULT:-null}" = null ];
then
        qjackctl -s &
	sleep 4
else
        echo "Already running"
fi

echo

echo "Starting Fluxus..."

optirun_exists () {
	type "optirun" &> /dev/null ;
}


if optirun_exists;
then
	OPTIRUN="optirun"
	echo "Optirun detected"
fi

if (("$#" > 0));
then
	FILE=$1
else
	FILE="FluxusBros.scm"
fi

$OPTIRUN fluxus -x $FILE
