(define (horwirequartertracker id cross)
    (let*
        (
            (tuioControl (c "points" id #:type "Tuio"))
            (tuioCursors (PersistentTuioCursor tuioControl (* (c "persistTuioDelay" id) 10)))
        )
;; (show "quartertracker tuio")
;; (show tuioCursors)
        (unless (empty? tuioCursors)
        ;(show tuioCursors)
            (flxseed 1)
            (let*
                (
                    (gainC (* (c "gain" id) 30))
                    (gain-wire (* (c "gain-wire" id) 0.01))
                    (firstBand (c "firstBand" id))
                    (secondBand (c "secondBand" id))
                    (ghOffset (c "gh-offset" id))
                    (sizeAll (* (c "size-all" id) 1))
                    (sizeCenter (* (c "center" id) 2))
                    (rotateList (map (lambda (r) (* 180 r)) (list (c "rotate-1" id) (c "rotate-2" id) (c "rotate-3" id))))
                    (rotate90 (* 90 (c "rotate-4" id)))
                    (tuioPoints (CalibrateTuioCursors tuioCursors (* 20 (c "tuioX" id)) (* 20 (c "tuioY" id)) (- (* 20 (c "tuioOffsetX" id)) 10) (- (* 20 (c "tuioOffsetY" id)) 10)))
                    (sortPoints (sort tuioPoints < #:key (lambda (p) (vector-ref p 0))))
                    (lengthPoints (length tuioPoints))
                    (halfPoints (/ lengthPoints 2))
                    (ceilhalfPoints (ceiling halfPoints))
                    (floorhalfPoints (floor halfPoints))
                    (symPoints (range (* floorhalfPoints -1) (+ floorhalfPoints 1) (max (/ (+ floorhalfPoints floorhalfPoints) (max 1 (- lengthPoints 1))) 1)))
                    (ghCoeff (/ (get-num-frequency-bins) (max (+ (floor halfPoints) 1))))
                    (ghPoints (map (lambda (p) (+ (* ghCoeff (abs p)) ghOffset)) symPoints))
                    ;(link-opa (c "link-opacity" id))
;;                     (link-opacity (c "link-opacity" id))
;;                     (link-gain (c "link-gain" id))
;;                     (tempGa (vector->list (vmul (ga) link-gain)))
;;                     (nGa (length tempGa))
                )
                (for-each
                    (lambda (point ghPoint)
                        (let*
                            (
                                (rotateBand (+ rotate90 (list-ref rotateList (inexact->exact (floor (* 3 (flxrnd)))))))
                                (size-y (gl ghPoint gainC))
                                (size-y-first (* firstBand size-y))
                                (size-y-second (* secondBand size-y))
                            )
                            (for-each
                                (lambda (freq)
                                    (with-state
                                        (hint-normalise)
                                        (translate point)
                                        (rotate (vector 0 0 (+ rotateBand 180)))
                                        (translate (vector 0 (/ size-y-first 2) 0))
                                        (translate (vmul (vector (gh freq) 0 0) gain-wire))
                                        (scale (vector sizeAll size-y-first sizeAll))
                                        (draw-cube)
                                    )
                                    (with-state
                                        (hint-normalise)
                                        (translate point)
                                        (rotate (vector 0 0 (+ rotateBand 180)))
                                        (translate (vector 0 (/ size-y-first 2) 0))
                                        (translate (vmul (vector (gh freq) 0 0) (* -1 gain-wire)))
                                        (scale (vector sizeAll size-y-first sizeAll))
                                        (draw-cube)
                                    )
                                    (with-state
                                        (hint-normalise)
                                        (translate point)
                                        (rotate (vector 0 0 rotateBand))
                                        (translate (vector 0 (/ size-y-second 2) 0))
                                        (translate (vmul (vector (gh freq) 0 0) gain-wire))
                                        (scale (vector sizeAll size-y-second sizeAll))
                                        (draw-cube)
                                    )
                                    (with-state
                                        (hint-normalise)
                                        (translate point)
                                        (rotate (vector 0 0 rotateBand))
                                        (translate (vector 0 (/ size-y-second 2) 0))
                                        (translate (vmul (vector (gh freq) 0 0) (* -1 gain-wire)))
                                        (scale (vector sizeAll size-y-second sizeAll))
                                        (draw-cube)
                                    )
                                )
                                (build-list (get-num-frequency-bins) values)
                            )
                        )
                    )
                    sortPoints
                    ghPoints
                )
            )
        )
    )
    #t
)