(define (cross-cube id crosss)
    (let
        (
            (g (c "gain" id))
            (blur (c "blur" id))
            (swith-line (c "switch-line" id))
            (opa-a (c "opa-a" id))
            (opa-b (c "opa-b" id))
            (color-r (c "color-r" id))
            (scale-r (c "scale-r" id))
            (color-v (c "color-v" id))
            (scale-v (c "scale-v" id))
            (color-b (c "color-b" id))
            (scale-b (c "scale-b" id))
        )
    (let
        (
            (croix
                (lambda (n))
                    (unless (zero? n)
                        (with-state
                            (opacity (max2 (+ opa (* opa-b (gh2 9 g))) (opa-cross crosss)))
                            (translate (vector (gl 1 g) 0 0))
                            (scale (vector (gl 1 g) (gl 1 g) (gl 9 g)))
                            (colour (vmul (vector (gl 1 g) 0.05 0) color-r))
                            (scale (vmul (vector 1 1 1) scale-r))
                            (draw-cube)
                            (croix (- n 1)))
                        (with-state
                            (opacity (max2 (+ opa-a (* (c opa-b id) (gl 9 g))) (opa-cross crosss)))
                            (translate (vector (* -1 (gl 1 g)) 0 0))
                            (scale (vector (gh2 1 g) (gh2 1 g) (gh2 9 g)))
                            (colour (vmul (vector (gl 1 g) 0.05 0) color-r))
                            (scale (vmul (vector 1 1 1) scale-r))
                            (draw-cube)
                            (croix (- n 1)))
                        (with-state
                            (opacity (max2 (+ opa-a (* opa-b (gl 6 g))) (opa-cross crosss)))
                            (translate (vector 0 (gl 3 g) 0))
                            (scale (vector (gl 3 g) (gl 6 g) (gl 3 g)))
                            (colour (vmul (vector 0 (gl 3 g) 0) color-v))
                            (scale (vmul (vector 1 1 1) scale-v))
                            (draw-cube)
                            (croix (- n 1)))
                        (with-state
                            (opacity (max2 (+ opa-a (* opa-b (gh2 6 g))) (opa-cross crosss)))
                            (translate (vector 0 (* -1 (gl 3 g)) 0))
                            (scale (vector (gl 6 g) (gl 6 g) (gl 3 g)))
                            (colour (vmul (vector 0 (gl 3 g) 0) color-v))
                            (scale (vmul (vector 1 1 1) scale-v))
                            (draw-cube)
                            (croix (- n 1)))
                        (with-state
                            (opacity (max2 (+ opa-a (* opa-b (gh2 1 g))) (opa-cross crosss)))
                            (translate (vector 0 0 (* 1 (gl 6 g))))
                            (scale (vector (gl 6 g) (gl 9 g) (gl 6 g)))
                            (colour (vmul (vector (gl 6 g) 0 (gl 6 g)) color-b))
                            (scale (vmul (vector 1 1 1) scale-b))
                            (draw-cube)
                            (croix (- n 1)))
                        (with-state
                            (opacity (max2 (+ opa-a (* opa-b (gl 1 g))) (opa-cross crosss)))
                            (translate (vector 0 0 (* -1 (gl 6 g))))
                            (scale (vector (gl 6 g) (gl 9 g) (gl 6 g)))
                            (colour (vmul (vector (gl 6 g) 0 (gl 6 g)) color-b))
                            (scale (vmul (vector 1 1 1) scale-b))
                            (draw-cube)
                            (cross (- n 1)))
                    )
                )
            )
        )
        (push)
;        (shinyness (m chann 14))
        (cond ((= 0 switch-line)
                (wire-opacity 0))
            (else
                (wire-opacity 1)
                (line-width (+ 0.1 (* switch-line 10)))))
        (croix 2)
        (pop)
    )
    )
)