(require "beat-module.scm")

(define pyr (load-primitive "square-pyramide.obj"))
(grab pyr)
(hide 1)
(ungrab)

(define transform-cube-hash (make-hash))

(define (transform-cube-destroy id)
    (destroy (hash-ref transform-cube-hash id))
    (hash-remove! transform-cube-hash id)
)

(define (transform-cube id cross)
;(show "")
;(show id)
;(show transform-cube-hash)
;(show (string? id))
    (unless (hash-has-key? transform-cube-hash id)
        (hash-set! transform-cube-hash id (build-disk 20))
    )
    (let
        (
            (b (c "blur" id))
            (g (c "gain" id))
        )
        (letrec
            (
                (num-id
                    (lambda ()
                        (+
                            (string->number (substring id 0 3))
                            (string->number (substring id 4))
                        )
                    )
                )
                (flxrndX
                    (lambda ()
;                        (flxseed (inexact->exact (round (+ (num-id) (time)))))
                        (flxseed (+ (num-id) (vector-ref (midi-position) 0) (vector-ref (midi-position) 1)))
                        (flxrnd)
                    )
                )
                (flxrndY
                    (lambda ()
;                        (flxseed (inexact->exact (round (+ .5 (num-id) (time)))))
                        (flxseed (+ (num-id) (vector-ref (midi-position) 0)))
                        (flxrnd)
                    )
                )
                (flxrndposX       
                    (lambda ()
                        (* (- (* 2 (flxrndX)) 1) 10)
                    )
                )
                (flxrndposY
                    (lambda ()
                        (* (- (* 2 (flxrndY)) 1) 6)
                    )
                )
                (posrnd
                    (lambda ()
                        (translate (vector (flxrndposX) (flxrndposY) 0))
                    )
                )
                (draw
                    (lambda ()
;                        (push)
                        (with-primitive (hash-ref transform-cube-hash id)
                            (identity)
;                            (blur 0.4)
(blur b)
                            (hint-wire)
                            (hint-ignore-depth)
                            (line-width 20)
                            (scale (vector 1 1 1))
                            (posrnd)
                            (scale (gl 5 g))
                            (colour (hsv->rgb (vector (flxrndY) 1 (* .5 (gl 5 g)))))
                            (wire-colour (hsv->rgb (vector (flxrndY) 1 1)))
                            (opacity (* .1 (gl 5 g)))
                            (wire-opacity (gl 5 g))
;                        (draw-instance transform-cube-prim)
;                        (pop)
                        )
                    )
                )
            )
            (draw)
;            (show threshold)
        )
    )
)

;(every-frame (transform-cube 1 1))
